library("tidyverse")
library("hexbin")
library("maps")
library("scales")
library("nycflights13")
library("HistData")
library("DiagrammeR")
library("Lahman")
library("prophet")
library("modelr")
library("nlme")
# Needed for Rendering R Markdown
library("bitops")
library("caTools")
library("shiny")